### ISSUE TITLE
Error in Library 

### ISSUE THREAD

**Issue by puneetv05** [StevenRudenko/ActionsContentView#34]
Got this error when i opened example.xml (ActionsContentView Example)

The following classes could not be instantiated:
- shared.ui.actionscontentview.ActionsContentView (Open Class, Show Error Log)
  See the Error Log (Window > Show View) for more details.
  Tip: Use View.isInEditMode() in your custom views to skip code when shown in Eclipse

android.content.res.Resources$NotFoundException: Could not resolve resource value: 0x7F060000.
    at android.content.res.BridgeResources.throwException(BridgeResources.java:693)
    at android.content.res.BridgeResources.getDimensionPixelSize(BridgeResources.java:406)
    at shared.ui.actionscontentview.ActionsContentView.<init>(ActionsContentView.java:169)
    at shared.ui.actionscontentview.ActionsContentView.<init>(ActionsContentView.java:157)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(    at sun.reflect.NativeConstructorAccessorImpl.newInstance(    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(    at java.lang.reflect.Constructor.newInstance(    at com.android.ide.eclipse.adt.internal.editors.layout.ProjectCallback.instantiateClass(ProjectCallback.java:422)
    at com.android.ide.eclipse.adt.internal.editors.layout.ProjectCallback.loadView(ProjectCallback.java:179)
    at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:207)
    at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:135)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:746)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:718)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:372)

**Comment by puneetv05** [comment]
and same error in other apps too

**Comment by StevenRudenko** [comment]
It seems you have not imported ActionsContentViewLib project in workspace you use for applications.
Please import it to same workspace where AcrionsContentViewExample is and try again.

**Comment by puneetv05** [comment]
hmm I just imported manually and tried  project prop. reference to Library also but when compiling same error occurred. :( 
any other suggestion ?

**Comment by StevenRudenko** [comment]
There is issue with missed resource value for R.dimen.default_actionscontentview_spacing. Could you check that you have it set at library or application projects?

**Comment by puneetv05** [comment]
hmm  which one I have to choose - import project module dependencies or import library?

**Comment by StevenRudenko** [comment]
1. Clone GitHub somewhere
2. Open Eclipse workspace
3. Press menu File->Import->Android->Existing Android code into workspace
4. Import ActionsContentViewLib project
5. Import ActionsContentViewExample project

You are done. It should work well now.

**Comment by puneetv05** [comment]
why I have to Import ActionsContentViewExample project ?

**Comment by StevenRudenko** [comment]
Please try my example first to see how it works. After that you would probably find problem in your code or configuration.

**Comment by puneetv05** [comment]
ya got it thanks Steven Rudenko
but How I import your library in my project?

**Comment by StevenRudenko** [comment]
1. Clone GitHub somewhere
2. Open Eclipse workspace
3. Press menu File->Import->Android->Existing Android code into workspace
4. Import ActionsContentViewLib project
5. Select your project and press menu Project->Properties
6. Select Android.
7. Press Add at Library section. Select ActionsContentViewLib.
8. Apply->OK

Now you can use it in your project.

**Comment by puneetv05** [comment]
:+1: Thanks :)

**Comment by StevenRudenko** [comment]
did you get ActionsContentView work with your project?

**Comment by tahaelearner** [comment]
Getting this error "Android requires compiler compliance level 5.0 or 6.0. Found '1.7' instead. Please use Android Tools > Fix Project Properties."

**Comment by StevenRudenko** [comment]
It is your Eclipse configuration problem.
Please use following steps to resolve issue:
1. Open workspace with project
2. Select project
3. Press menu: Project->Properties
4. Goto tab Java Compiler
5. Check 'Enable project specific settings'
6. Set 'Compiler compliance level' to 1.6
7. Apply - OK

Do this for all Android projects or workspace setting and problem should be resolved.

**Comment by puneetv05** [comment]
Set Compiler level to 1.6. and check you Environment Variable Path for JAVA
