### ISSUE TITLE
java.lang.NoClassDefFoundError: shared.ui.actionscontentview.R$styleable

### ISSUE THREAD

**Issue by swapps** [StevenRudenko/ActionsContentView#44]
hi, some of my app users are getting this error as soon as they try to launch an actionscontentview.

Do you have an idea how to solve it ?

```
java.lang.NoClassDefFoundError: shared.ui.actionscontentview.R$styleable
at shared.ui.actionscontentview.ActionsContentView.<init>(ActionsContentView.java:169)
at shared.ui.actionscontentview.ActionsContentView.<init>(ActionsContentView.java:159)
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at android.view.LayoutInflater.createView(LayoutInflater.java:587)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
at android.view.LayoutInflater.inflate(Native Method)
at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:286)
at android.app.Activity.setContentView(Activity.java:1881)
at com.preiss.swapps.link.Adapters.NotifActivity.onCreate(NotifActivity.java:104)
at android.app.Activity.performCreate(Activity.java:5122)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
at android.app.ActivityThread.access$600(ActivityThread.java:162)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5371)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by StevenRudenko** [comment]
Hello,

It seems that there is styles.xml missed for some device configurations.
Please make sure that it is available at res/values folder in your project.

Kind regards,
Steven

## 

Steven Rudenko | Software engineer
e. steven.rudenko@gmail.com | p. +380 63 2636053
