### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by bilalsaeed** [StevenRudenko/ActionsContentView#47]
Hello Steven,

I am using android studio and when I run your example code I get null pointer exception.
Caused by: java.lang.NullPointerException
            at sample.actionscontentview.ExamplesActivity.onCreate(ExamplesActivity.java:60)
            at android.app.Activity.performCreate(Activity.java:5426)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

here is the line 60: viewActionsList.setAdapter(actionsAdapter);

I would really appreciate your response.

thanks,
Bilal Saeed.

**Comment by StevenRudenko** [comment]
Hello Bilal,

I've checked current project state and it seems it works fine for me. According to what I see at exception stacktrace there is actions listview missed. Please check that you've added it to action.xml
